CREATE TABLE [Customer]
(
  [Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  [FirstName] VARCHAR(40) NOT NULL,
  [LastName] VARCHAR(40) NOT NULL,
  [Document] CHAR(11) NOT NULL,
  [Email] VARCHAR(160) NOT NULL,
  [CreatedOn] DATETIME NOT NULL DEFAULT(GETDATE()),
  [UpdatedOn] DATETIME NOT NULL DEFAULT(GETDATE()),
)

CREATE TABLE [Address]
(
  [Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  [CustomerId] UNIQUEIDENTIFIER NOT NULL,
  [Number] VARCHAR(10) NOT NULL,
  [Street] VARCHAR(40) NOT NULL,
  [District] VARCHAR(60) NOT NULL,
  [City] VARCHAR(60) NOT NULL,
  [State] CHAR(2) NOT NULL,
  [Country] CHAR(2) NOT NULL,
  [ZipCode] CHAR(8) NOT NULL,
  FOREIGN KEY ([CustomerId]) REFERENCES [Customer]([Id]),
  [CreatedOn] DATETIME NOT NULL DEFAULT(GETDATE()),
  [UpdatedOn] DATETIME NOT NULL DEFAULT(GETDATE()),
)

CREATE TABLE [Product]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Name] VARCHAR(250) NOT NULL,
	[Description] VARCHAR(500) NOT NULL,
	[Active] BIT NOT NULL,
	[Price] DECIMAL(10, 2) NOT NULL,
	[ImageUrl] VARCHAR(250) NOT NULL,
	[StockQuantity] INT NOT NULL,
  [CreatedOn] DATETIME NOT NULL DEFAULT(GETDATE()),
  [UpdatedOn] DATETIME NOT NULL DEFAULT(GETDATE()),
)
